package com.netty.model.player.minigame.impetuousimpulses;

public enum Impling {

	BABY_IMPLING, YOUNG_IMPLING, GOURMET_IMPLING, EARTH_IMPLING, ESSENCE_IMPLING, ELECTIC_IMPLING, SPIRIT_IMPLING, NATURE_IMPLING, MAGPIE_IMPLING,
	NINJA_IMPLING, PIRATE_IMPLING, DRAGON_IMPLING, ZOMBIE_IMPLING, KINGLY_IMPLING;
}